### ISSUE TITLE
needs -moz-box-sizing: border-box for firefox

### ISSUE THREAD

**Issue by millermedeiros** [piuccio/rocambole-visualize#1]
otherwise columns doesn't float (padding conflicts with it)

``` css
.pure-g > div {
  -moz-box-sizing: border-box;
  box-sizing: border-box;
}
```
